### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by Kolmain** [MarlBurroW/google-home-notification-center#2]
Can we get a docker container that builds from this repo for automated deployments?

**Comment by ajayjohn** [comment]
I second this. Would greatly ease the deployment and update process.

**Comment by MarlBurroW** [comment]
Yes, sounds like a great idea. I'll try to dockerize it.

**Comment by MarlBurroW** [comment]
I created a Docker Image here: https://hub.docker.com/r/marlburrow/ghng/

- image: `marlburrow/ghng`
- Private port to map on your host: `3000`

Here is my Dockerfile used to build the image: https://github.com/MarlBurroW/google-home-notification-gateway/tree/master/docker-production

My DevOps skills are really limited so I've not managed to make a lighter image (440 MB), I am open to any proposal to improve it.
